#
# Module manifest for module 'pNTFSPermission'
#
# Generated by: Monte Hazboun
#
# Generated on: 6/22/2016
#
#

@{

# Version number of this module.
ModuleVersion = '1.2.0'

# ID used to uniquely identify this module
GUID = '346600c9-a59e-4337-9c2a-483104f808e3'

# Author of this module
Author = 'Monte Hazboun'

# Company or vendor of this module
CompanyName = 'Publix Super Markets'

# Copyright statement for this module
Copyright = '(c) 2016 Publix Super Markets. All rights reserved.'

# Description of the functionality provided by this module
Description = 'DSC module to manipulate NTFS permissions on a system file or folder.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
#NestedModules = @(pNTFSPermission.psm1)

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

}